spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/demo1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/homeworkDB
    username: postgres
    password: root

  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: create
        show_sql: true

server:
  port: 9000
logging:
  level:
    root: info
    com.dhabits: debug
    org:
      springframework:
        security: debug
  config: classpath:logback-local.xml
keycloak:
  realm: demo1
  resource: app
  auth-server-url: http://localhost:8081/




